export const racesDataFake = {
  head: [
    {
      "1": "Grand Prix",
      "2": "Date",
      "3": "Winner",
      "4": "Car",
      "5": "Laps",
      "6": "Time",
    },
  ],
  body: [
    {
      "1": "Bahrain",
      "2": "05 Mar 2023",
      "3": "Max Verstappen VER",
      "4": "Red Bull Racing Honda RBPT",
      "5": "57",
      "6": "1:33:56.736",
    },
    {
      "1": "Saudi Arabia",
      "2": "19 Mar 2023",
      "3": "Sergio Perez PER",
      "4": "Red Bull Racing Honda RBPT",
      "5": "50",
      "6": "1:21:14.894",
    },
    {
      "1": "Australia",
      "2": "02 Apr 2023",
      "3": "Max Verstappen VER",
      "4": "Red Bull Racing Honda RBPT",
      "5": "58",
      "6": "2:32:38.371",
    },
    {
      "1": "Azerbaijan",
      "2": "30 Apr 2023",
      "3": "Sergio Perez PER",
      "4": "Red Bull Racing Honda RBPT",
      "5": "51",
      "6": "1:32:42.436",
    },
    {
      "1": "Miami",
      "2": "07 May 2023",
      "3": "Max Verstappen VER",
      "4": "Red Bull Racing Honda RBPT",
      "5": "57",
      "6": "1:27:38.241",
    },
    {
      "1": "Monaco",
      "2": "28 May 2023",
      "3": "Max Verstappen VER",
      "4": "Red Bull Racing Honda RBPT",
      "5": "78",
      "6": "1:48:51.980",
    },
    {
      "1": "Spain",
      "2": "04 Jun 2023",
      "3": "Max Verstappen VER",
      "4": "Red Bull Racing Honda RBPT",
      "5": "66",
      "6": "1:27:57.940",
    },
  ],
};

export const driversDataFake = {
  head: [
    {
      "1": "Pos",
      "2": "Driver",
      "3": "Nationality",
      "4": "Car",
      "5": "PTS",
      "6": "",
    },
  ],
  body: [
    {
      "1": "1",
      "2": "Max Verstappen VER",
      "3": "NED",
      "4": "Red Bull Racing Honda RBPT",
      "5": "170",
      "6": "",
    },
    {
      "1": "2",
      "2": "Sergio Perez PER",
      "3": "MEX",
      "4": "Red Bull Racing Honda RBPT",
      "5": "117",
      "6": "",
    },
    {
      "1": "3",
      "2": "Fernando Alonso ALO",
      "3": "ESP",
      "4": "Aston Martin Aramco Mercedes",
      "5": "99",
      "6": "",
    },
    {
      "1": "4",
      "2": "Lewis Hamilton HAM",
      "3": "GBR",
      "4": "Mercedes",
      "5": "87",
      "6": "",
    },
    {
      "1": "5",
      "2": "George Russell RUS",
      "3": "GBR",
      "4": "Mercedes",
      "5": "65",
      "6": "",
    },
    {
      "1": "6",
      "2": "Carlos Sainz SAI",
      "3": "ESP",
      "4": "Ferrari",
      "5": "58",
      "6": "",
    },
    {
      "1": "7",
      "2": "Charles Leclerc LEC",
      "3": "MON",
      "4": "Ferrari",
      "5": "42",
      "6": "",
    },
    {
      "1": "8",
      "2": "Lance Stroll STR",
      "3": "CAN",
      "4": "Aston Martin Aramco Mercedes",
      "5": "35",
      "6": "",
    },
    {
      "1": "9",
      "2": "Esteban Ocon OCO",
      "3": "FRA",
      "4": "Alpine Renault",
      "5": "25",
      "6": "",
    },
    {
      "1": "10",
      "2": "Pierre Gasly GAS",
      "3": "FRA",
      "4": "Alpine Renault",
      "5": "15",
      "6": "",
    },
    {
      "1": "11",
      "2": "Lando Norris NOR",
      "3": "GBR",
      "4": "McLaren Mercedes",
      "5": "12",
      "6": "",
    },
    {
      "1": "12",
      "2": "Nico Hulkenberg HUL",
      "3": "GER",
      "4": "Haas Ferrari",
      "5": "6",
      "6": "",
    },
    {
      "1": "13",
      "2": "Oscar Piastri PIA",
      "3": "AUS",
      "4": "McLaren Mercedes",
      "5": "5",
      "6": "",
    },
    {
      "1": "14",
      "2": "Valtteri Bottas BOT",
      "3": "FIN",
      "4": "Alfa Romeo Ferrari",
      "5": "4",
      "6": "",
    },
    {
      "1": "15",
      "2": "Zhou Guanyu ZHO",
      "3": "CHN",
      "4": "Alfa Romeo Ferrari",
      "5": "4",
      "6": "",
    },
    {
      "1": "16",
      "2": "Yuki Tsunoda TSU",
      "3": "JPN",
      "4": "AlphaTauri Honda RBPT",
      "5": "2",
      "6": "",
    },
    {
      "1": "17",
      "2": "Kevin Magnussen MAG",
      "3": "DEN",
      "4": "Haas Ferrari",
      "5": "2",
      "6": "",
    },
    {
      "1": "18",
      "2": "Alexander Albon ALB",
      "3": "THA",
      "4": "Williams Mercedes",
      "5": "1",
      "6": "",
    },
    {
      "1": "19",
      "2": "Nyck De Vries DEV",
      "3": "NED",
      "4": "AlphaTauri Honda RBPT",
      "5": "0",
      "6": "",
    },
    {
      "1": "20",
      "2": "Logan Sargeant SAR",
      "3": "USA",
      "4": "Williams Mercedes",
      "5": "0",
      "6": "",
    },
  ],
};
